type Recipe {
  id: ID!
  title: String!
  description: String
  steps: [ Step! ]!
  createdAt: AWSDateTime!
}

type Step {
  description: String!
  time: AWSTime
}

extend type Query {
  getRecipes: [ Recipe! ]
  getRecipe(id: ID!): Recipe
}

input RecipeInput {
  title: String!
  description: String
  steps: [ AddStepInput! ]!
  createdAt: AWSDateTime
}

input AddStepInput {
  description: String!
  time: AWSTime
}

extend type Mutation {
  addRecipe(input: RecipeInput!): Recipe
}